# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: lint-client

on:
  push:
    branches: ["main"]
    paths:
      - "tatara/**"
  pull_request:
    branches: ["main"]
    paths:
      - "tatara/**"

permissions:
  contents: read

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tatara

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies using Poetry
        run: |
          poetry install --no-root

      - name: Typecheck with pyright
        run: |
          poetry run pyright .

      - name: Lint with ruff
        run: |
          poetry run ruff check .
